root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./src/go/"
bin = "tmp/parser"
# Customize binary.
full_bin = "APP_ENV=dev APP_USER=AndreyFurman ./tmp/main"
delay = 0 #ms
exclude_dir = ['node_modules', 'env', 'data', 'src/node', 'src/python']
include_dir = []
include_ext = ['go']
stop_on_error = true
log = "tmp/air.log"

[log]
# Show log time
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
