version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:14.17

jobs:
  check_py:
    executor: node
    steps:
      - run: python3 --version

workflows:
  initial:
    jobs:
      - check_py
